"""
Questions to answer:
    - What crop is the most profitable under _any_ circumstances? What are those circumstances?
    - What crop is the most valuable within any given season?
    - What crop is the most valuable in any given season when you consider inter-season growth?
    - When is it more profitable to use a seed maker to get your seeds?
    - When is it more profitable to use the seedmaker to turn the crop into seeds and sell them?
    - When is fertilizer profitable?
    - When is speed-gro profitable?
    - What is the most profitable series of crops to plant at the beginning of the game?
    - Is it more profitable to leave crops that can become giant crops after maturity?

Inputs:
    - What seed
    - Seed source
        - already owned / don't include
        - vendor
    - Use seed maker at harvest?
    - What is the growth interval? A certain season or number of days or growth cycles?
    - Player info
    - Soil modifiers?
    * Crop layout

Functions:
    - Calc growth cycles
        - return number of growth cycles that can happen with the given crop in the given number of days    
    - Harvest
        - return crops/items generated in the given number of growth cycles
        - return amount of xp from harvesting
    - Post-process
        - return items generated by running th given items through post-processing
        - return the time that it took to post-process
    - Sell
        - calculate the return on selling a given item or series of items

Requirements:
    - Need to know what post-processing an item can receive and what item will be produced
    - Need to know 

"""